version: '3.7'

services:
  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TZ=Europe/Oslo
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${HOME}/.ssh:/var/jenkins_home/.ssh:rw
      - ${HOME}/.m2:/var/jenkins_home/.m2:rw
    secrets:
      - JENKINS_SSH_PRIVATE_KEY
    env_file: ./jenkins/secrets.env
    depends_on:
      - agent-java
      - slapd

  agent-java:
    build:
      context: ./agent-java/
      dockerfile: Dockerfile
    container_name: 'agent-java'
    hostname: 'agent-java'
    ports:
      - 22:22
    environment:
      - JENKINS_AGENT_SSH_PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4a5IBmV1jdssc8nrCWcFwpK++c1wicaY9aVY3VXnRSQvl5TmuluXg44ARWjGNVe9nRiprj5sUe0FnGJkk4Dglc1+ZC6i69dGt+NneGGtgt63+hwJZrQ3AtgK33YQLrSsfaEHqVtON8TTyAt5sN94Jq7tP24pdKhwGl7/HZFsRR4tGrQQPGuxAbhHZpVClAZ6cf0woky66cQa9iQSNO6apC4wH6kP8RFOcTI0aJNysKwf5ioXNXPiKvKhAZKpqd269wIWThfvJv9Qk9dU2W1EtIQGwZn/EfzxtJcGe/PnHmN8jiTPzMGCjX9JeKMTphUpz5BSGK+XzWcg1vcd/BK/NwxMNLPS91AgGw65qi2WGcV34vcWVH0uRE8smCS2FeKjBxD/iLYcwEBkH7SNcnvU4pII7JsE8ueJV6CHTf9sT/orYgU4CHgIDdxQiVZSWthNBAVxLOZVedEumRdolDaTQMvbMnDhW5r1GLwsIAtFDKCtpry0r+10FCqW332SKE6HZ++QUWQn6gN7BDfV+4X8ZTpQCw3dyeRaoYq1lVeNke2dwXgus+Vl8H86AeXkr43TeRGYkvW08shrvn9mUw3rPKHWi/fKcJFEYvSePcEan5AtnVPZrPZhZV04Xu7Jj6MVrkklhVkNw3kvjLo0iO1pfDX07vKuA1rNPHbMFigIIJw== sheeeng@gmail.com

  slapd:
    build:
      context: ./slapd
    ports:
      - 389:389
      - 636:636

  phpldapadmin:
    image: osixia/phpldapadmin:0.8.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: slapd
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - 8090:80
    depends_on:
      - slapd

  nexus:
    build:
      context: ./nexus
    ports:
      - 8081:8081
    volumes:
      - nexus_data:/nexus-data

secrets:
  JENKINS_SSH_PRIVATE_KEY:
    file: ~/.ssh/id_rsa

volumes:
  jenkins_home:
  nexus_data:
