version: '3.7'

services:
  jenkins:
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TZ=Europe/Oslo
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
